### ISSUE TITLE
Image list information to be included as image properties in glance

### ISSUE THREAD

**Issue by enolfc** [the-cloudkeeper-project/cloudkeeper-os#23]
cloudkeeper-os now dumps image information coming from the VO-wide image list into an APPLIANCE_ATTRIBUTES property of the image in glance. This is nice but in order to make efficient queries, it would be good if most or all of these could be added directly as attributed. 

I'm specially interested in "ad:appid" attribute as this helps to find the right image independently of the versions in AppDB.

**Comment by Pansanel** [comment]
This feature has been added in:
https://github.com/FranceGrilles/cloudkeeper-os/tree/0.9.16
