### ISSUE TITLE
Avoid using "voms.json" in the mapping file name

### ISSUE THREAD

**Issue by enolfc** [the-cloudkeeper-project/cloudkeeper-os#24]
cloudkeeper-os uses voms.json file to map VOs to local projects, but we no longer depend on VOMS. Would it make sense to change the default file name?

**Comment by Pansanel** [comment]
I would suggest ```group.json``` or ```mapping.json```. Do you have any suggestions?

**Comment by enolfc** [comment]
`mapping.json` seems good to me. 

Also, I would use `project` instead of `tenant` as these are Keystone v2 nomenclature

Another change to consider is using project ids instead of names (or allow to specify either project name + domain name or project id)

Now I turned this into 3 issues :(
