### ISSUE TITLE
Update of images using in environments with ceph as storage backend

### ISSUE THREAD

**Issue by Mamut3D** [the-cloudkeeper-project/cloudkeeper-os#8]
Hello,

I have tried the cloudkeeper-os and it uploads new images just fine, however the code fails during the update of images. I believe it is becaue ceph images cannot be updated, since they are used as read only base for the their VM clones.

What storage backend do you use - LVM? 

The code fails during the update proces on lin 149 in cloudkeeper-os/cloudkeeper_os/imagemanager.py
        glance.images.upload(glance_image.id, image_data)

[errlog.txt](https://github.com/the-cloudkeeper-project/cloudkeeper-os/files/1187764/errlog.txt)

**Comment by Pansanel** [comment]
Hello,
I am effectively using the LVM backend. I may add a specific try/except uround glance.images.upload.
Jerome

**Comment by Mamut3D** [comment]
I did a bit of research around the issue, and I am not sure if the image update should be possible this way even for LVM - does it work for you instance?
So far, I have read, that the best practice to update image is either delete and create new, or just create new.
Do you manage public images with this tool? Because I would like to manage public images wit this and https://rubygems.org/gems/imagemaster3000 , but that requires some automatic public attributre handling...

**Comment by Pansanel** [comment]
It seems to work for LVM. I may change the code to perform a delete/add instead of updating.
The developer of imagemaster is the same than for Cloudkeeper :-)
I am managing my images with Cloudkeeper-os for all EGI related project.

**Comment by Pansanel** [comment]
A new version of Cloudkeeper-OS has been released:
http://grand-est.fr/resources/software/cloudkeeper-os/centos7/x86_64/cloudkeeper-os-0.9.4-1.el7.centos.x86_64.rpm

This version include a fix for the image update.
